# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_my.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.obj_get_data = QtWidgets.QTextEdit(self.centralwidget)
        self.obj_get_data.setGeometry(QtCore.QRect(310, 0, 491, 301))
        self.obj_get_data.setObjectName("obj_get_data")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 360, 54, 12))
        self.label_4.setObjectName("label_4")
        self.obj_send_data = QtWidgets.QTextEdit(self.centralwidget)
        self.obj_send_data.setGeometry(QtCore.QRect(310, 380, 481, 111))
        self.obj_send_data.setObjectName("obj_send_data")
        self.obj_send_cmd = QtWidgets.QPushButton(self.centralwidget)
        self.obj_send_cmd.setGeometry(QtCore.QRect(310, 500, 75, 23))
        self.obj_send_cmd.setObjectName("obj_send_cmd")
        self.obj_recv_clear = QtWidgets.QPushButton(self.centralwidget)
        self.obj_recv_clear.setGeometry(QtCore.QRect(310, 310, 75, 23))
        self.obj_recv_clear.setObjectName("obj_recv_clear")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 530, 791, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.obj_sta = QtWidgets.QLineEdit(self.layoutWidget)
        self.obj_sta.setObjectName("obj_sta")
        self.horizontalLayout_3.addWidget(self.obj_sta)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 10, 119, 103))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.obj_com_port = QtWidgets.QComboBox(self.layoutWidget1)
        self.obj_com_port.setObjectName("obj_com_port")
        self.horizontalLayout.addWidget(self.obj_com_port)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.obj_com_baud = QtWidgets.QComboBox(self.layoutWidget1)
        self.obj_com_baud.setObjectName("obj_com_baud")
        self.horizontalLayout_2.addWidget(self.obj_com_baud)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.obj_com_on_off = QtWidgets.QPushButton(self.layoutWidget1)
        self.obj_com_on_off.setObjectName("obj_com_on_off")
        self.verticalLayout_2.addWidget(self.obj_com_on_off)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(180, 10, 77, 43))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.obj_wifi_on_off = QtWidgets.QPushButton(self.layoutWidget2)
        self.obj_wifi_on_off.setObjectName("obj_wifi_on_off")
        self.gridLayout_2.addWidget(self.obj_wifi_on_off, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "输入"))
        self.obj_send_cmd.setText(_translate("MainWindow", "发送"))
        self.obj_recv_clear.setText(_translate("MainWindow", "清空显示"))
        self.label_3.setText(_translate("MainWindow", "状态"))
        self.label_5.setText(_translate("MainWindow", "蓝牙串口连接"))
        self.label.setText(_translate("MainWindow", "串口号"))
        self.label_2.setText(_translate("MainWindow", "波特率"))
        self.obj_com_on_off.setText(_translate("MainWindow", "打开"))
        self.label_6.setText(_translate("MainWindow", "WiFi连接"))
        self.obj_wifi_on_off.setText(_translate("MainWindow", "打开"))

